# Generated by Django 4.2.1 on 2023-06-04 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 18, 11, 37, 73498, tzinfo=datetime.timezone.utc), verbose_name='date_published'),
        ),
    ]
